<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260322162703 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create short_url table with code, original_url, created_at, and user_id columns';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE short_url (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(10) NOT NULL, original_url VARCHAR(2048) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8336053177153098 ON short_url (code)');
        $this->addSql('CREATE INDEX IDX_83360531A76ED395 ON short_url (user_id)');
        $this->addSql('ALTER TABLE short_url ADD CONSTRAINT FK_83360531A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE short_url DROP CONSTRAINT FK_83360531A76ED395');
        $this->addSql('DROP TABLE short_url');
    }
}
