<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260322180810 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create click table with ip, user_agent, and created_at columns';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE click (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ip VARCHAR(45) NOT NULL, user_agent VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE click');
    }
}
